---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: buster64
    box: debian/buster64
  - name: centos7
    box: centos/7
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  become: true
verifier:
  name: goss
